// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: heartbeat.proto
#ifndef GRPC_heartbeat_2eproto__INCLUDED
#define GRPC_heartbeat_2eproto__INCLUDED

#include "heartbeat.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace heartbeat {

class Heartbeat final {
 public:
  static constexpr char const* service_full_name() {
    return "heartbeat.Heartbeat";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientWriterInterface< ::heartbeat::Beat>> Monitor(::grpc::ClientContext* context, ::heartbeat::MonitorReply* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::heartbeat::Beat>>(MonitorRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::heartbeat::Beat>> AsyncMonitor(::grpc::ClientContext* context, ::heartbeat::MonitorReply* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::heartbeat::Beat>>(AsyncMonitorRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::heartbeat::Beat>> PrepareAsyncMonitor(::grpc::ClientContext* context, ::heartbeat::MonitorReply* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::heartbeat::Beat>>(PrepareAsyncMonitorRaw(context, response, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Monitor(::grpc::ClientContext* context, ::heartbeat::MonitorReply* response, ::grpc::ClientWriteReactor< ::heartbeat::Beat>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientWriterInterface< ::heartbeat::Beat>* MonitorRaw(::grpc::ClientContext* context, ::heartbeat::MonitorReply* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::heartbeat::Beat>* AsyncMonitorRaw(::grpc::ClientContext* context, ::heartbeat::MonitorReply* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::heartbeat::Beat>* PrepareAsyncMonitorRaw(::grpc::ClientContext* context, ::heartbeat::MonitorReply* response, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientWriter< ::heartbeat::Beat>> Monitor(::grpc::ClientContext* context, ::heartbeat::MonitorReply* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::heartbeat::Beat>>(MonitorRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::heartbeat::Beat>> AsyncMonitor(::grpc::ClientContext* context, ::heartbeat::MonitorReply* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::heartbeat::Beat>>(AsyncMonitorRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::heartbeat::Beat>> PrepareAsyncMonitor(::grpc::ClientContext* context, ::heartbeat::MonitorReply* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::heartbeat::Beat>>(PrepareAsyncMonitorRaw(context, response, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Monitor(::grpc::ClientContext* context, ::heartbeat::MonitorReply* response, ::grpc::ClientWriteReactor< ::heartbeat::Beat>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientWriter< ::heartbeat::Beat>* MonitorRaw(::grpc::ClientContext* context, ::heartbeat::MonitorReply* response) override;
    ::grpc::ClientAsyncWriter< ::heartbeat::Beat>* AsyncMonitorRaw(::grpc::ClientContext* context, ::heartbeat::MonitorReply* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::heartbeat::Beat>* PrepareAsyncMonitorRaw(::grpc::ClientContext* context, ::heartbeat::MonitorReply* response, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Monitor_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Monitor(::grpc::ServerContext* context, ::grpc::ServerReader< ::heartbeat::Beat>* reader, ::heartbeat::MonitorReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Monitor : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Monitor() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Monitor() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Monitor(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::heartbeat::Beat>* /*reader*/, ::heartbeat::MonitorReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMonitor(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::heartbeat::MonitorReply, ::heartbeat::Beat>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Monitor<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Monitor : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Monitor() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::heartbeat::Beat, ::heartbeat::MonitorReply>(
            [this](
                   ::grpc::CallbackServerContext* context, ::heartbeat::MonitorReply* response) { return this->Monitor(context, response); }));
    }
    ~WithCallbackMethod_Monitor() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Monitor(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::heartbeat::Beat>* /*reader*/, ::heartbeat::MonitorReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::heartbeat::Beat>* Monitor(
      ::grpc::CallbackServerContext* /*context*/, ::heartbeat::MonitorReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Monitor<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Monitor : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Monitor() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Monitor() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Monitor(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::heartbeat::Beat>* /*reader*/, ::heartbeat::MonitorReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Monitor : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Monitor() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Monitor() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Monitor(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::heartbeat::Beat>* /*reader*/, ::heartbeat::MonitorReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMonitor(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Monitor : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Monitor() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->Monitor(context, response); }));
    }
    ~WithRawCallbackMethod_Monitor() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Monitor(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::heartbeat::Beat>* /*reader*/, ::heartbeat::MonitorReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* Monitor(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace heartbeat


#endif  // GRPC_heartbeat_2eproto__INCLUDED
