// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: heartbeat.proto

#include "heartbeat.pb.h"
#include "heartbeat.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace heartbeat {

static const char* Heartbeat_method_names[] = {
  "/heartbeat.Heartbeat/Monitor",
};

std::unique_ptr< Heartbeat::Stub> Heartbeat::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Heartbeat::Stub> stub(new Heartbeat::Stub(channel, options));
  return stub;
}

Heartbeat::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Monitor_(Heartbeat_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::ClientWriter< ::heartbeat::Beat>* Heartbeat::Stub::MonitorRaw(::grpc::ClientContext* context, ::heartbeat::MonitorReply* response) {
  return ::grpc::internal::ClientWriterFactory< ::heartbeat::Beat>::Create(channel_.get(), rpcmethod_Monitor_, context, response);
}

void Heartbeat::Stub::async::Monitor(::grpc::ClientContext* context, ::heartbeat::MonitorReply* response, ::grpc::ClientWriteReactor< ::heartbeat::Beat>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::heartbeat::Beat>::Create(stub_->channel_.get(), stub_->rpcmethod_Monitor_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::heartbeat::Beat>* Heartbeat::Stub::AsyncMonitorRaw(::grpc::ClientContext* context, ::heartbeat::MonitorReply* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::heartbeat::Beat>::Create(channel_.get(), cq, rpcmethod_Monitor_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::heartbeat::Beat>* Heartbeat::Stub::PrepareAsyncMonitorRaw(::grpc::ClientContext* context, ::heartbeat::MonitorReply* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::heartbeat::Beat>::Create(channel_.get(), cq, rpcmethod_Monitor_, context, response, false, nullptr);
}

Heartbeat::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Heartbeat_method_names[0],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< Heartbeat::Service, ::heartbeat::Beat, ::heartbeat::MonitorReply>(
          [](Heartbeat::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::heartbeat::Beat>* reader,
             ::heartbeat::MonitorReply* resp) {
               return service->Monitor(ctx, reader, resp);
             }, this)));
}

Heartbeat::Service::~Service() {
}

::grpc::Status Heartbeat::Service::Monitor(::grpc::ServerContext* context, ::grpc::ServerReader< ::heartbeat::Beat>* reader, ::heartbeat::MonitorReply* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace heartbeat

