// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heartbeat.proto

#include "heartbeat.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace heartbeat {

inline constexpr MonitorReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : ok_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MonitorReply::MonitorReply(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MonitorReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MonitorReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MonitorReplyDefaultTypeInternal() {}
  union {
    MonitorReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MonitorReplyDefaultTypeInternal _MonitorReply_default_instance_;

inline constexpr Beat::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        timestamp_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Beat::Beat(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct BeatDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BeatDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BeatDefaultTypeInternal() {}
  union {
    Beat _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BeatDefaultTypeInternal _Beat_default_instance_;
}  // namespace heartbeat
static ::_pb::Metadata file_level_metadata_heartbeat_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_heartbeat_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_heartbeat_2eproto = nullptr;
const ::uint32_t TableStruct_heartbeat_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::heartbeat::Beat, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::heartbeat::Beat, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::heartbeat::Beat, _impl_.timestamp_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::heartbeat::MonitorReply, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::heartbeat::MonitorReply, _impl_.ok_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::heartbeat::Beat)},
        {10, -1, -1, sizeof(::heartbeat::MonitorReply)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::heartbeat::_Beat_default_instance_._instance,
    &::heartbeat::_MonitorReply_default_instance_._instance,
};
const char descriptor_table_protodef_heartbeat_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\017heartbeat.proto\022\theartbeat\"%\n\004Beat\022\n\n\002"
    "id\030\001 \001(\t\022\021\n\ttimestamp\030\002 \001(\t\"\032\n\014MonitorRe"
    "ply\022\n\n\002ok\030\001 \001(\0102D\n\tHeartbeat\0227\n\007Monitor\022"
    "\017.heartbeat.Beat\032\027.heartbeat.MonitorRepl"
    "y\"\000(\001B\rZ\013./heartbeatb\006proto3"
};
static ::absl::once_flag descriptor_table_heartbeat_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_heartbeat_2eproto = {
    false,
    false,
    188,
    descriptor_table_protodef_heartbeat_2eproto,
    "heartbeat.proto",
    &descriptor_table_heartbeat_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_heartbeat_2eproto::offsets,
    file_level_metadata_heartbeat_2eproto,
    file_level_enum_descriptors_heartbeat_2eproto,
    file_level_service_descriptors_heartbeat_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_heartbeat_2eproto_getter() {
  return &descriptor_table_heartbeat_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_heartbeat_2eproto(&descriptor_table_heartbeat_2eproto);
namespace heartbeat {
// ===================================================================

class Beat::_Internal {
 public:
};

Beat::Beat(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:heartbeat.Beat)
}
inline PROTOBUF_NDEBUG_INLINE Beat::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : id_(arena, from.id_),
        timestamp_(arena, from.timestamp_),
        _cached_size_{0} {}

Beat::Beat(
    ::google::protobuf::Arena* arena,
    const Beat& from)
    : ::google::protobuf::Message(arena) {
  Beat* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:heartbeat.Beat)
}
inline PROTOBUF_NDEBUG_INLINE Beat::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : id_(arena),
        timestamp_(arena),
        _cached_size_{0} {}

inline void Beat::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Beat::~Beat() {
  // @@protoc_insertion_point(destructor:heartbeat.Beat)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Beat::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.id_.Destroy();
  _impl_.timestamp_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void Beat::Clear() {
// @@protoc_insertion_point(message_clear_start:heartbeat.Beat)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_.ClearToEmpty();
  _impl_.timestamp_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Beat::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 34, 2> Beat::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Beat_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string timestamp = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Beat, _impl_.timestamp_)}},
    // string id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Beat, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string id = 1;
    {PROTOBUF_FIELD_OFFSET(Beat, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string timestamp = 2;
    {PROTOBUF_FIELD_OFFSET(Beat, _impl_.timestamp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\16\2\11\0\0\0\0\0"
    "heartbeat.Beat"
    "id"
    "timestamp"
  }},
};

::uint8_t* Beat::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:heartbeat.Beat)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string id = 1;
  if (!this->_internal_id().empty()) {
    const std::string& _s = this->_internal_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "heartbeat.Beat.id");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string timestamp = 2;
  if (!this->_internal_timestamp().empty()) {
    const std::string& _s = this->_internal_timestamp();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "heartbeat.Beat.timestamp");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:heartbeat.Beat)
  return target;
}

::size_t Beat::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:heartbeat.Beat)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string id = 1;
  if (!this->_internal_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_id());
  }

  // string timestamp = 2;
  if (!this->_internal_timestamp().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_timestamp());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Beat::_class_data_ = {
    Beat::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Beat::GetClassData() const {
  return &_class_data_;
}

void Beat::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Beat*>(&to_msg);
  auto& from = static_cast<const Beat&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:heartbeat.Beat)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_id().empty()) {
    _this->_internal_set_id(from._internal_id());
  }
  if (!from._internal_timestamp().empty()) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Beat::CopyFrom(const Beat& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:heartbeat.Beat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Beat::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* Beat::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Beat::InternalSwap(Beat* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.id_, &other->_impl_.id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.timestamp_, &other->_impl_.timestamp_, arena);
}

::google::protobuf::Metadata Beat::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_heartbeat_2eproto_getter, &descriptor_table_heartbeat_2eproto_once,
      file_level_metadata_heartbeat_2eproto[0]);
}
// ===================================================================

class MonitorReply::_Internal {
 public:
};

MonitorReply::MonitorReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:heartbeat.MonitorReply)
}
MonitorReply::MonitorReply(
    ::google::protobuf::Arena* arena, const MonitorReply& from)
    : MonitorReply(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE MonitorReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void MonitorReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.ok_ = {};
}
MonitorReply::~MonitorReply() {
  // @@protoc_insertion_point(destructor:heartbeat.MonitorReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MonitorReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void MonitorReply::Clear() {
// @@protoc_insertion_point(message_clear_start:heartbeat.MonitorReply)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ok_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* MonitorReply::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> MonitorReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_MonitorReply_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bool ok = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(MonitorReply, _impl_.ok_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MonitorReply, _impl_.ok_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool ok = 1;
    {PROTOBUF_FIELD_OFFSET(MonitorReply, _impl_.ok_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* MonitorReply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:heartbeat.MonitorReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool ok = 1;
  if (this->_internal_ok() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_ok(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:heartbeat.MonitorReply)
  return target;
}

::size_t MonitorReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:heartbeat.MonitorReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool ok = 1;
  if (this->_internal_ok() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData MonitorReply::_class_data_ = {
    MonitorReply::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* MonitorReply::GetClassData() const {
  return &_class_data_;
}

void MonitorReply::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<MonitorReply*>(&to_msg);
  auto& from = static_cast<const MonitorReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:heartbeat.MonitorReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_ok() != 0) {
    _this->_internal_set_ok(from._internal_ok());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MonitorReply::CopyFrom(const MonitorReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:heartbeat.MonitorReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool MonitorReply::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* MonitorReply::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void MonitorReply::InternalSwap(MonitorReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.ok_, other->_impl_.ok_);
}

::google::protobuf::Metadata MonitorReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_heartbeat_2eproto_getter, &descriptor_table_heartbeat_2eproto_once,
      file_level_metadata_heartbeat_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace heartbeat
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
